#!/bin/sh

# Add driver repository
composer config --no-interaction repositories.scout-elasticsearch-driver \
    '{"type": "path", "url": "../driver", "options": {"symlink": true}}'

# Require driver package
composer require --no-interaction --prefer-dist babenkoivan/scout-elasticsearch-driver:@dev

# Clear application cache
php artisan cache:clear --no-interaction

# Run migrations
php artisan migrate --no-interaction --seed
